export const SHOW_LOGIN = 'SHOW_LOGIN'
export const HIDE_LOGIN = 'HIDE_LOGIN'
export const SHOW_CREATE_ACCOUNT = 'SHOW_CREATE_ACCOUNT'
export const HIDE_CREATE_ACCOUNT = 'HIDE_CREATE_ACCOUNT'
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const SHOW_CHART = 'SHOW_CHART'
export const HIDE_CHART = 'HIDE_CHART'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY'
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
